@file:Suppress(
    "ModifierOrdering",
    "CommentSpacing",
    "NoBlankLineBeforeRbrace",
    "ModifierOrdering",
    "NoConsecutiveBlankLines",
    "MagicNumber",
    "FunctionName",
    "MatchingDeclarationName",
    "LongParameterList",
    "SpacingAroundParens"
)

package com.flamingo.theme

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.res.painterResource
import com.flamingo.R
import com.flamingo.annotations.DelicateFlamingoApi
import com.flamingo.annotations.view.DsIconSet
import com.flamingo.components.Icon
import com.flamingo.view.requireDsIcon

@JvmInline
public value class FlamingoIcon private constructor(@DsIconSet private val resId: Int) {
    /**
     * Typically, you need to use a flamingo component, which directly consumes [FlamingoIcon]. For
     * example, use [Icon] composable instead of a material one. Use this function with care!
     */
    @DelicateFlamingoApi
    @Composable
    public fun toPainter(): Painter = painterResource(resId)

    /**
     * @return name of the icon in snake case without [DRAWABLE_NAME_PREFIX]
     */
    public fun getName(context: Context): String {
        return context.resources.getResourceEntryName(resId).removePrefix(DRAWABLE_NAME_PREFIX)
    }

    private companion object {
        private const val DRAWABLE_NAME_PREFIX: String = "ds_ic_"
    }

    @Suppress("VariableNaming")
    public class FlamingoIcons internal constructor() {
        public val DRAWABLE_NAME_PREFIX: String = FlamingoIcon.DRAWABLE_NAME_PREFIX

        public fun fromId(@DsIconSet resId: Int): FlamingoIcon {
            requireDsIcon(resId)
            return FlamingoIcon(resId)
        }

        /**
         * @param name of the icon in snake case, with or without [DRAWABLE_NAME_PREFIX]
         */
        public fun fromName(context: Context, name: String): FlamingoIcon = FlamingoIcon(
            resId = context.resources.getIdentifier(
                DRAWABLE_NAME_PREFIX + name.removePrefix(DRAWABLE_NAME_PREFIX),
                "drawable",
                context.packageName
            )
        )

        /**
         * All properties call private constructor of the [FlamingoIcon] ([I] for short).
         */
        @Suppress("NOTHING_TO_INLINE")
        private inline fun I(@DsIconSet resId: Int) = FlamingoIcon(resId)

        // Sorted alphabetically, use https://plugins.jetbrains.com/plugin/2162-string-manipulation

        public val Activity: FlamingoIcon = I(R.drawable.ds_ic_activity)
        public val Agile: FlamingoIcon = I(R.drawable.ds_ic_agile)
        public val Airplay: FlamingoIcon = I(R.drawable.ds_ic_airplay)
        public val AlertCircle: FlamingoIcon = I(R.drawable.ds_ic_alert_circle)
        public val AlertOctagon: FlamingoIcon = I(R.drawable.ds_ic_alert_octagon)
        public val AlertTriangle: FlamingoIcon = I(R.drawable.ds_ic_alert_triangle)
        public val AlertTriangleFilled: FlamingoIcon = I(R.drawable.ds_ic_alert_triangle_filled)
        public val AlignCenter: FlamingoIcon = I(R.drawable.ds_ic_align_center)
        public val AlignJustify: FlamingoIcon = I(R.drawable.ds_ic_align_justify)
        public val AlignLeft: FlamingoIcon = I(R.drawable.ds_ic_align_left)
        public val AlignRight: FlamingoIcon = I(R.drawable.ds_ic_align_right)
        public val Anchor: FlamingoIcon = I(R.drawable.ds_ic_anchor)
        public val Android: FlamingoIcon = I(R.drawable.ds_ic_android)
        public val Aperture: FlamingoIcon = I(R.drawable.ds_ic_aperture)
        public val Archive: FlamingoIcon = I(R.drawable.ds_ic_archive)
        public val ArrowDown: FlamingoIcon = I(R.drawable.ds_ic_arrow_down)
        public val ArrowDownCircle: FlamingoIcon = I(R.drawable.ds_ic_arrow_down_circle)
        public val ArrowDownLeft: FlamingoIcon = I(R.drawable.ds_ic_arrow_down_left)
        public val ArrowDownRight: FlamingoIcon = I(R.drawable.ds_ic_arrow_down_right)
        public val ArrowDropDown: FlamingoIcon = I(R.drawable.ds_ic_arrow_drop_down)
        public val ArrowLeft: FlamingoIcon = I(R.drawable.ds_ic_arrow_left)
        public val ArrowLeftCircle: FlamingoIcon = I(R.drawable.ds_ic_arrow_left_circle)
        public val ArrowRight: FlamingoIcon = I(R.drawable.ds_ic_arrow_right)
        public val ArrowRightCircle: FlamingoIcon = I(R.drawable.ds_ic_arrow_right_circle)
        public val ArrowUp: FlamingoIcon = I(R.drawable.ds_ic_arrow_up)
        public val ArrowUpCircle: FlamingoIcon = I(R.drawable.ds_ic_arrow_up_circle)
        public val ArrowUpLeft: FlamingoIcon = I(R.drawable.ds_ic_arrow_up_left)
        public val ArrowUpRight: FlamingoIcon = I(R.drawable.ds_ic_arrow_up_right)
        public val AtmCard: FlamingoIcon = I(R.drawable.ds_ic_atm_card)
        public val AtSign: FlamingoIcon = I(R.drawable.ds_ic_at_sign)
        public val Award: FlamingoIcon = I(R.drawable.ds_ic_award)
        public val Baby: FlamingoIcon = I(R.drawable.ds_ic_baby)
        public val BarChart2: FlamingoIcon = I(R.drawable.ds_ic_bar_chart_2)
        public val BarChart: FlamingoIcon = I(R.drawable.ds_ic_bar_chart)
        public val Battery: FlamingoIcon = I(R.drawable.ds_ic_battery)
        public val BatteryCharging: FlamingoIcon = I(R.drawable.ds_ic_battery_charging)
        public val Bell: FlamingoIcon = I(R.drawable.ds_ic_bell)
        public val BellOff: FlamingoIcon = I(R.drawable.ds_ic_bell_off)
        public val Bluetooth: FlamingoIcon = I(R.drawable.ds_ic_bluetooth)
        public val Bold: FlamingoIcon = I(R.drawable.ds_ic_bold)
        public val Book: FlamingoIcon = I(R.drawable.ds_ic_book)
        public val Bookmark: FlamingoIcon = I(R.drawable.ds_ic_bookmark)
        public val BookmarkFilled: FlamingoIcon = I(R.drawable.ds_ic_bookmark_filled)
        public val BookOpen: FlamingoIcon = I(R.drawable.ds_ic_book_open)
        public val Box: FlamingoIcon = I(R.drawable.ds_ic_box)
        public val Briefcase: FlamingoIcon = I(R.drawable.ds_ic_briefcase)
        public val BriefcaseFilledV2: FlamingoIcon = I(R.drawable.ds_ic_briefcase_filled_v2)
        public val BriefcaseV2: FlamingoIcon = I(R.drawable.ds_ic_briefcase_v2)
        public val Calendar: FlamingoIcon = I(R.drawable.ds_ic_calendar)
        public val Camera: FlamingoIcon = I(R.drawable.ds_ic_camera)
        public val CameraFilled: FlamingoIcon = I(R.drawable.ds_ic_camera_filled)
        public val CameraOff: FlamingoIcon = I(R.drawable.ds_ic_camera_off)
        public val CancelInCircleFilled: FlamingoIcon = I(R.drawable.ds_ic_cancel_in_circle_filled)
        public val Cast: FlamingoIcon = I(R.drawable.ds_ic_cast)
        public val ChartSquare: FlamingoIcon = I(R.drawable.ds_ic_chart_square)
        public val Check: FlamingoIcon = I(R.drawable.ds_ic_check)
        public val CheckCircle: FlamingoIcon = I(R.drawable.ds_ic_check_circle)
        public val CheckCircleV3: FlamingoIcon = I(R.drawable.ds_ic_check_circle_v3)
        public val CheckSquare: FlamingoIcon = I(R.drawable.ds_ic_check_square)
        public val CheckSquareMinusV2: FlamingoIcon = I(R.drawable.ds_ic_check_square_minus_v2)
        public val CheckSquareMinusV3: FlamingoIcon = I(R.drawable.ds_ic_check_square_minus_v3)
        public val CheckSquareV3: FlamingoIcon = I(R.drawable.ds_ic_check_square_v3)
        public val ChevronDown: FlamingoIcon = I(R.drawable.ds_ic_chevron_down)
        public val ChevronLeft: FlamingoIcon = I(R.drawable.ds_ic_chevron_left)
        public val ChevronRight: FlamingoIcon = I(R.drawable.ds_ic_chevron_right)
        public val ChevronsDown: FlamingoIcon = I(R.drawable.ds_ic_chevrons_down)
        public val ChevronsLeft: FlamingoIcon = I(R.drawable.ds_ic_chevrons_left)
        public val ChevronsRight: FlamingoIcon = I(R.drawable.ds_ic_chevrons_right)
        public val ChevronsUp: FlamingoIcon = I(R.drawable.ds_ic_chevrons_up)
        public val ChevronUp: FlamingoIcon = I(R.drawable.ds_ic_chevron_up)
        public val Chrome: FlamingoIcon = I(R.drawable.ds_ic_chrome)
        public val Circle: FlamingoIcon = I(R.drawable.ds_ic_circle)
        public val CircleV2: FlamingoIcon = I(R.drawable.ds_ic_circle_v2)
        public val Clipboard: FlamingoIcon = I(R.drawable.ds_ic_clipboard)
        public val Clock: FlamingoIcon = I(R.drawable.ds_ic_clock)
        public val Cloud: FlamingoIcon = I(R.drawable.ds_ic_cloud)
        public val CloudDrizzle: FlamingoIcon = I(R.drawable.ds_ic_cloud_drizzle)
        public val CloudLightning: FlamingoIcon = I(R.drawable.ds_ic_cloud_lightning)
        public val CloudOff: FlamingoIcon = I(R.drawable.ds_ic_cloud_off)
        public val CloudRain: FlamingoIcon = I(R.drawable.ds_ic_cloud_rain)
        public val CloudSnow: FlamingoIcon = I(R.drawable.ds_ic_cloud_snow)
        public val Code: FlamingoIcon = I(R.drawable.ds_ic_code)
        public val Codepen: FlamingoIcon = I(R.drawable.ds_ic_codepen)
        public val Codesandbox: FlamingoIcon = I(R.drawable.ds_ic_codesandbox)
        public val Coffee: FlamingoIcon = I(R.drawable.ds_ic_coffee)
        public val Columns: FlamingoIcon = I(R.drawable.ds_ic_columns)
        public val Command: FlamingoIcon = I(R.drawable.ds_ic_command)
        public val Compass: FlamingoIcon = I(R.drawable.ds_ic_compass)
        public val Copy: FlamingoIcon = I(R.drawable.ds_ic_copy)
        public val CornerDownLeft: FlamingoIcon = I(R.drawable.ds_ic_corner_down_left)
        public val CornerDownRight: FlamingoIcon = I(R.drawable.ds_ic_corner_down_right)
        public val CornerLeftDown: FlamingoIcon = I(R.drawable.ds_ic_corner_left_down)
        public val CornerLeftUp: FlamingoIcon = I(R.drawable.ds_ic_corner_left_up)
        public val CornerRightDown: FlamingoIcon = I(R.drawable.ds_ic_corner_right_down)
        public val CornerRightUp: FlamingoIcon = I(R.drawable.ds_ic_corner_right_up)
        public val CornerUpLeft: FlamingoIcon = I(R.drawable.ds_ic_corner_up_left)
        public val CornerUpRight: FlamingoIcon = I(R.drawable.ds_ic_corner_up_right)
        public val Cpu: FlamingoIcon = I(R.drawable.ds_ic_cpu)
        public val CreditCard: FlamingoIcon = I(R.drawable.ds_ic_credit_card)
        public val Crop: FlamingoIcon = I(R.drawable.ds_ic_crop)
        public val Crosshair: FlamingoIcon = I(R.drawable.ds_ic_crosshair)
        public val Database: FlamingoIcon = I(R.drawable.ds_ic_database)
        public val Delete: FlamingoIcon = I(R.drawable.ds_ic_delete)
        public val Disc: FlamingoIcon = I(R.drawable.ds_ic_disc)
        public val Divide: FlamingoIcon = I(R.drawable.ds_ic_divide)
        public val DivideCircle: FlamingoIcon = I(R.drawable.ds_ic_divide_circle)
        public val DivideSquare: FlamingoIcon = I(R.drawable.ds_ic_divide_square)
        public val DollarSign: FlamingoIcon = I(R.drawable.ds_ic_dollar_sign)
        public val DoneInCircleFilled: FlamingoIcon = I(R.drawable.ds_ic_done_in_circle_filled)
        public val Download: FlamingoIcon = I(R.drawable.ds_ic_download)
        public val DownloadCloud: FlamingoIcon = I(R.drawable.ds_ic_download_cloud)
        public val Draggable: FlamingoIcon = I(R.drawable.ds_ic_draggable)
        public val Dribbble: FlamingoIcon = I(R.drawable.ds_ic_dribbble)
        public val Droplet: FlamingoIcon = I(R.drawable.ds_ic_droplet)
        public val Edit2: FlamingoIcon = I(R.drawable.ds_ic_edit_2)
        public val Edit3: FlamingoIcon = I(R.drawable.ds_ic_edit_3)
        public val Edit: FlamingoIcon = I(R.drawable.ds_ic_edit)
        public val ExternalLink: FlamingoIcon = I(R.drawable.ds_ic_external_link)
        public val Eye: FlamingoIcon = I(R.drawable.ds_ic_eye)
        public val EyeOff: FlamingoIcon = I(R.drawable.ds_ic_eye_off)
        public val Facebook: FlamingoIcon = I(R.drawable.ds_ic_facebook)
        public val FaceId: FlamingoIcon = I(R.drawable.ds_ic_face_id)
        public val FastForward: FlamingoIcon = I(R.drawable.ds_ic_fast_forward)
        public val Feather: FlamingoIcon = I(R.drawable.ds_ic_feather)
        public val Feedback: FlamingoIcon = I(R.drawable.ds_ic_feedback)
        public val FeedbackService: FlamingoIcon = I(R.drawable.ds_ic_feedback_service)
        public val Figma: FlamingoIcon = I(R.drawable.ds_ic_figma)
        public val File: FlamingoIcon = I(R.drawable.ds_ic_file)
        public val FileMinus: FlamingoIcon = I(R.drawable.ds_ic_file_minus)
        public val FilePlus: FlamingoIcon = I(R.drawable.ds_ic_file_plus)
        public val FileText: FlamingoIcon = I(R.drawable.ds_ic_file_text)
        public val Film: FlamingoIcon = I(R.drawable.ds_ic_film)
        public val Filter: FlamingoIcon = I(R.drawable.ds_ic_filter)
        public val Flag: FlamingoIcon = I(R.drawable.ds_ic_flag)
        public val Folder: FlamingoIcon = I(R.drawable.ds_ic_folder)
        public val FolderFilled: FlamingoIcon = I(R.drawable.ds_ic_folder_filled)
        public val FolderMinus: FlamingoIcon = I(R.drawable.ds_ic_folder_minus)
        public val FolderPlus: FlamingoIcon = I(R.drawable.ds_ic_folder_plus)
        public val Framer: FlamingoIcon = I(R.drawable.ds_ic_framer)
        public val Frown: FlamingoIcon = I(R.drawable.ds_ic_frown)
        public val Gift: FlamingoIcon = I(R.drawable.ds_ic_gift)
        public val GitBranch: FlamingoIcon = I(R.drawable.ds_ic_git_branch)
        public val GitCommit: FlamingoIcon = I(R.drawable.ds_ic_git_commit)
        public val Github: FlamingoIcon = I(R.drawable.ds_ic_github)
        public val Gitlab: FlamingoIcon = I(R.drawable.ds_ic_gitlab)
        public val GitMerge: FlamingoIcon = I(R.drawable.ds_ic_git_merge)
        public val GitPullRequest: FlamingoIcon = I(R.drawable.ds_ic_git_pull_request)
        public val Globe: FlamingoIcon = I(R.drawable.ds_ic_globe)
        public val GlobeSearch: FlamingoIcon = I(R.drawable.ds_ic_globe_search)
        public val Grid: FlamingoIcon = I(R.drawable.ds_ic_grid)
        public val GridFilledV2: FlamingoIcon = I(R.drawable.ds_ic_grid_filled_v2)
        public val GridV2: FlamingoIcon = I(R.drawable.ds_ic_grid_v2)
        public val H2: FlamingoIcon = I(R.drawable.ds_ic_h2)
        public val H3: FlamingoIcon = I(R.drawable.ds_ic_h3)
        public val HardDrive: FlamingoIcon = I(R.drawable.ds_ic_hard_drive)
        public val Hash: FlamingoIcon = I(R.drawable.ds_ic_hash)
        public val Headphones: FlamingoIcon = I(R.drawable.ds_ic_headphones)
        public val Heart: FlamingoIcon = I(R.drawable.ds_ic_heart)
        public val HeartFilled: FlamingoIcon = I(R.drawable.ds_ic_heart_filled)
        public val HelpCircle: FlamingoIcon = I(R.drawable.ds_ic_help_circle)
        public val HelpCircleFilled: FlamingoIcon = I(R.drawable.ds_ic_help_circle_filled)
        public val Hexagon: FlamingoIcon = I(R.drawable.ds_ic_hexagon)
        public val Home: FlamingoIcon = I(R.drawable.ds_ic_home)
        public val HomeFilled: FlamingoIcon = I(R.drawable.ds_ic_home_filled)
        public val HomeFilledV2: FlamingoIcon = I(R.drawable.ds_ic_home_filled_v2)
        public val HomeV2: FlamingoIcon = I(R.drawable.ds_ic_home_v2)
        public val Idea: FlamingoIcon = I(R.drawable.ds_ic_idea)
        public val Image: FlamingoIcon = I(R.drawable.ds_ic_image)
        public val Inbox: FlamingoIcon = I(R.drawable.ds_ic_inbox)
        public val InboxFilled: FlamingoIcon = I(R.drawable.ds_ic_inbox_filled)
        public val Incognito: FlamingoIcon = I(R.drawable.ds_ic_incognito)
        public val Info: FlamingoIcon = I(R.drawable.ds_ic_info)
        public val Instagram: FlamingoIcon = I(R.drawable.ds_ic_instagram)
        public val Ios: FlamingoIcon = I(R.drawable.ds_ic_ios)
        public val Italic: FlamingoIcon = I(R.drawable.ds_ic_italic)
        public val Key: FlamingoIcon = I(R.drawable.ds_ic_key)
        public val Layers: FlamingoIcon = I(R.drawable.ds_ic_layers)
        public val Layout: FlamingoIcon = I(R.drawable.ds_ic_layout)
        public val LifeBuoy: FlamingoIcon = I(R.drawable.ds_ic_life_buoy)
        public val Link2: FlamingoIcon = I(R.drawable.ds_ic_link_2)
        public val Link: FlamingoIcon = I(R.drawable.ds_ic_link)
        public val Linkedin: FlamingoIcon = I(R.drawable.ds_ic_linkedin)
        public val List: FlamingoIcon = I(R.drawable.ds_ic_list)
        public val ListNumber: FlamingoIcon = I(R.drawable.ds_ic_list_number)
        public val Loader: FlamingoIcon = I(R.drawable.ds_ic_loader)
        public val Lock: FlamingoIcon = I(R.drawable.ds_ic_lock)
        public val LockFilled: FlamingoIcon = I(R.drawable.ds_ic_lock_filled)
        public val LogIn: FlamingoIcon = I(R.drawable.ds_ic_log_in)
        public val LogOut: FlamingoIcon = I(R.drawable.ds_ic_log_out)
        public val Mail: FlamingoIcon = I(R.drawable.ds_ic_mail)
        public val Map: FlamingoIcon = I(R.drawable.ds_ic_map)
        public val MapPin: FlamingoIcon = I(R.drawable.ds_ic_map_pin)
        public val Maximize2: FlamingoIcon = I(R.drawable.ds_ic_maximize_2)
        public val Maximize: FlamingoIcon = I(R.drawable.ds_ic_maximize)
        public val Meh: FlamingoIcon = I(R.drawable.ds_ic_meh)
        public val Menu: FlamingoIcon = I(R.drawable.ds_ic_menu)
        public val MessageCircle: FlamingoIcon = I(R.drawable.ds_ic_message_circle)
        public val MessageSquare: FlamingoIcon = I(R.drawable.ds_ic_message_square)
        public val MessageSquareFilled: FlamingoIcon = I(R.drawable.ds_ic_message_square_filled)
        public val Mic: FlamingoIcon = I(R.drawable.ds_ic_mic)
        public val MicOff: FlamingoIcon = I(R.drawable.ds_ic_mic_off)
        public val Minimize2: FlamingoIcon = I(R.drawable.ds_ic_minimize_2)
        public val Minimize: FlamingoIcon = I(R.drawable.ds_ic_minimize)
        public val Minus: FlamingoIcon = I(R.drawable.ds_ic_minus)
        public val MinusCircle: FlamingoIcon = I(R.drawable.ds_ic_minus_circle)
        public val MinusSquare: FlamingoIcon = I(R.drawable.ds_ic_minus_square)
        public val Monitor: FlamingoIcon = I(R.drawable.ds_ic_monitor)
        public val Moon: FlamingoIcon = I(R.drawable.ds_ic_moon)
        public val MoreHorizontal: FlamingoIcon = I(R.drawable.ds_ic_more_horizontal)
        public val MoreVertical: FlamingoIcon = I(R.drawable.ds_ic_more_vertical)
        public val MousePointer: FlamingoIcon = I(R.drawable.ds_ic_mouse_pointer)
        public val Move: FlamingoIcon = I(R.drawable.ds_ic_move)
        public val Music: FlamingoIcon = I(R.drawable.ds_ic_music)
        public val Navigation2: FlamingoIcon = I(R.drawable.ds_ic_navigation_2)
        public val Navigation: FlamingoIcon = I(R.drawable.ds_ic_navigation)
        public val Octagon: FlamingoIcon = I(R.drawable.ds_ic_octagon)
        public val Orgchart: FlamingoIcon = I(R.drawable.ds_ic_orgchart)
        public val Package: FlamingoIcon = I(R.drawable.ds_ic_package)
        public val Paperclip: FlamingoIcon = I(R.drawable.ds_ic_paperclip)
        public val Pause: FlamingoIcon = I(R.drawable.ds_ic_pause)
        public val PauseCircle: FlamingoIcon = I(R.drawable.ds_ic_pause_circle)
        public val PenTool: FlamingoIcon = I(R.drawable.ds_ic_pen_tool)
        public val Percent: FlamingoIcon = I(R.drawable.ds_ic_percent)
        public val Phone: FlamingoIcon = I(R.drawable.ds_ic_phone)
        public val PhoneCall: FlamingoIcon = I(R.drawable.ds_ic_phone_call)
        public val PhoneForwarded: FlamingoIcon = I(R.drawable.ds_ic_phone_forwarded)
        public val PhoneIncoming: FlamingoIcon = I(R.drawable.ds_ic_phone_incoming)
        public val PhoneMissed: FlamingoIcon = I(R.drawable.ds_ic_phone_missed)
        public val PhoneOff: FlamingoIcon = I(R.drawable.ds_ic_phone_off)
        public val PhoneOutgoing: FlamingoIcon = I(R.drawable.ds_ic_phone_outgoing)
        public val PieChart: FlamingoIcon = I(R.drawable.ds_ic_pie_chart)
        public val PinFilled: FlamingoIcon = I(R.drawable.ds_ic_pin_filled)
        public val PinOutline: FlamingoIcon = I(R.drawable.ds_ic_pin_outline)
        public val Play: FlamingoIcon = I(R.drawable.ds_ic_play)
        public val PlayCircle: FlamingoIcon = I(R.drawable.ds_ic_play_circle)
        public val Plus: FlamingoIcon = I(R.drawable.ds_ic_plus)
        public val PlusCircle: FlamingoIcon = I(R.drawable.ds_ic_plus_circle)
        public val PlusSquare: FlamingoIcon = I(R.drawable.ds_ic_plus_square)
        public val Pocket: FlamingoIcon = I(R.drawable.ds_ic_pocket)
        public val Power: FlamingoIcon = I(R.drawable.ds_ic_power)
        public val Printer: FlamingoIcon = I(R.drawable.ds_ic_printer)
        public val Qr: FlamingoIcon = I(R.drawable.ds_ic_qr)
        public val Radio: FlamingoIcon = I(R.drawable.ds_ic_radio)
        public val RefreshCcw: FlamingoIcon = I(R.drawable.ds_ic_refresh_ccw)
        public val RefreshCw: FlamingoIcon = I(R.drawable.ds_ic_refresh_cw)
        public val Repeat: FlamingoIcon = I(R.drawable.ds_ic_repeat)
        public val Replace: FlamingoIcon = I(R.drawable.ds_ic_replace)
        public val Reply: FlamingoIcon = I(R.drawable.ds_ic_reply)
        public val Repost: FlamingoIcon = I(R.drawable.ds_ic_repost)
        public val Rewind: FlamingoIcon = I(R.drawable.ds_ic_rewind)
        public val RotateCcw: FlamingoIcon = I(R.drawable.ds_ic_rotate_ccw)
        public val RotateCw: FlamingoIcon = I(R.drawable.ds_ic_rotate_cw)
        public val Rss: FlamingoIcon = I(R.drawable.ds_ic_rss)
        public val Salute: FlamingoIcon = I(R.drawable.ds_ic_salute)
        public val Save: FlamingoIcon = I(R.drawable.ds_ic_save)
        public val Sber: FlamingoIcon = I(R.drawable.ds_ic_sber)
        public val Sberchat: FlamingoIcon = I(R.drawable.ds_ic_sberchat)
        public val Scissors: FlamingoIcon = I(R.drawable.ds_ic_scissors)
        public val Search: FlamingoIcon = I(R.drawable.ds_ic_search)
        public val Send: FlamingoIcon = I(R.drawable.ds_ic_send)
        public val Server: FlamingoIcon = I(R.drawable.ds_ic_server)
        public val Settings: FlamingoIcon = I(R.drawable.ds_ic_settings)
        public val Share2: FlamingoIcon = I(R.drawable.ds_ic_share_2)
        public val Share: FlamingoIcon = I(R.drawable.ds_ic_share)
        public val Shield: FlamingoIcon = I(R.drawable.ds_ic_shield)
        public val ShieldOff: FlamingoIcon = I(R.drawable.ds_ic_shield_off)
        public val ShoppingBag: FlamingoIcon = I(R.drawable.ds_ic_shopping_bag)
        public val ShoppingCart: FlamingoIcon = I(R.drawable.ds_ic_shopping_cart)
        public val Shuffle: FlamingoIcon = I(R.drawable.ds_ic_shuffle)
        public val Sidebar: FlamingoIcon = I(R.drawable.ds_ic_sidebar)
        public val SidebarFilled: FlamingoIcon = I(R.drawable.ds_ic_sidebar_filled)
        public val SkipBack: FlamingoIcon = I(R.drawable.ds_ic_skip_back)
        public val SkipForward: FlamingoIcon = I(R.drawable.ds_ic_skip_forward)
        public val Slack: FlamingoIcon = I(R.drawable.ds_ic_slack)
        public val Slash: FlamingoIcon = I(R.drawable.ds_ic_slash)
        public val Sliders: FlamingoIcon = I(R.drawable.ds_ic_sliders)
        public val Smartphone: FlamingoIcon = I(R.drawable.ds_ic_smartphone)
        public val Smile: FlamingoIcon = I(R.drawable.ds_ic_smile)
        public val Sort: FlamingoIcon = I(R.drawable.ds_ic_sort)
        public val Speaker: FlamingoIcon = I(R.drawable.ds_ic_speaker)
        public val Square: FlamingoIcon = I(R.drawable.ds_ic_square)
        public val SquareV2: FlamingoIcon = I(R.drawable.ds_ic_square_v2)
        public val Star: FlamingoIcon = I(R.drawable.ds_ic_star)
        public val StarFilled: FlamingoIcon = I(R.drawable.ds_ic_star_filled)
        public val StarHalfFilled: FlamingoIcon = I(R.drawable.ds_ic_star_half_filled)
        public val StopCircle: FlamingoIcon = I(R.drawable.ds_ic_stop_circle)
        public val Sun: FlamingoIcon = I(R.drawable.ds_ic_sun)
        public val Sunrise: FlamingoIcon = I(R.drawable.ds_ic_sunrise)
        public val Sunset: FlamingoIcon = I(R.drawable.ds_ic_sunset)
        public val Tablet: FlamingoIcon = I(R.drawable.ds_ic_tablet)
        public val Tag: FlamingoIcon = I(R.drawable.ds_ic_tag)
        public val Target: FlamingoIcon = I(R.drawable.ds_ic_target)
        public val Terminal: FlamingoIcon = I(R.drawable.ds_ic_terminal)
        public val Thermometer: FlamingoIcon = I(R.drawable.ds_ic_thermometer)
        public val ThumbsDown: FlamingoIcon = I(R.drawable.ds_ic_thumbs_down)
        public val ThumbsDownFilled: FlamingoIcon = I(R.drawable.ds_ic_thumbs_down_filled)
        public val ThumbsUp: FlamingoIcon = I(R.drawable.ds_ic_thumbs_up)
        public val ThumbsUpFilled: FlamingoIcon = I(R.drawable.ds_ic_thumbs_up_filled)
        public val ToggleLeft: FlamingoIcon = I(R.drawable.ds_ic_toggle_left)
        public val ToggleRight: FlamingoIcon = I(R.drawable.ds_ic_toggle_right)
        public val Tool: FlamingoIcon = I(R.drawable.ds_ic_tool)
        public val TouchId: FlamingoIcon = I(R.drawable.ds_ic_touch_id)
        public val Trash2: FlamingoIcon = I(R.drawable.ds_ic_trash_2)
        public val Trash: FlamingoIcon = I(R.drawable.ds_ic_trash)
        public val Trello: FlamingoIcon = I(R.drawable.ds_ic_trello)
        public val TrendingDown: FlamingoIcon = I(R.drawable.ds_ic_trending_down)
        public val TrendingUp: FlamingoIcon = I(R.drawable.ds_ic_trending_up)
        public val Triangle: FlamingoIcon = I(R.drawable.ds_ic_triangle)
        public val Truck: FlamingoIcon = I(R.drawable.ds_ic_truck)
        public val Tv: FlamingoIcon = I(R.drawable.ds_ic_tv)
        public val Twitch: FlamingoIcon = I(R.drawable.ds_ic_twitch)
        public val Twitter: FlamingoIcon = I(R.drawable.ds_ic_twitter)
        public val Type: FlamingoIcon = I(R.drawable.ds_ic_type)
        public val Umbrella: FlamingoIcon = I(R.drawable.ds_ic_umbrella)
        public val Underline: FlamingoIcon = I(R.drawable.ds_ic_underline)
        public val Unlock: FlamingoIcon = I(R.drawable.ds_ic_unlock)
        public val Upload: FlamingoIcon = I(R.drawable.ds_ic_upload)
        public val UploadCloud: FlamingoIcon = I(R.drawable.ds_ic_upload_cloud)
        public val User: FlamingoIcon = I(R.drawable.ds_ic_user)
        public val UserAdmin: FlamingoIcon = I(R.drawable.ds_ic_user_admin)
        public val UserCheck: FlamingoIcon = I(R.drawable.ds_ic_user_check)
        public val UserFilled: FlamingoIcon = I(R.drawable.ds_ic_user_filled)
        public val UserMinus: FlamingoIcon = I(R.drawable.ds_ic_user_minus)
        public val UserPlus: FlamingoIcon = I(R.drawable.ds_ic_user_plus)
        public val Users: FlamingoIcon = I(R.drawable.ds_ic_users)
        public val UserX: FlamingoIcon = I(R.drawable.ds_ic_user_x)
        public val Video: FlamingoIcon = I(R.drawable.ds_ic_video)
        public val VideoHorizontally: FlamingoIcon = I(R.drawable.ds_ic_video_horizontally)
        public val VideoOff: FlamingoIcon = I(R.drawable.ds_ic_video_off)
        public val VideoSquare: FlamingoIcon = I(R.drawable.ds_ic_video_square)
        public val VideoStretch: FlamingoIcon = I(R.drawable.ds_ic_video_stretch)
        public val Voicemail: FlamingoIcon = I(R.drawable.ds_ic_voicemail)
        public val Volume1: FlamingoIcon = I(R.drawable.ds_ic_volume_1)
        public val Volume2: FlamingoIcon = I(R.drawable.ds_ic_volume_2)
        public val Volume: FlamingoIcon = I(R.drawable.ds_ic_volume)
        public val VolumeOff: FlamingoIcon = I(R.drawable.ds_ic_volume_off)
        public val VolumeX: FlamingoIcon = I(R.drawable.ds_ic_volume_x)
        public val Watch: FlamingoIcon = I(R.drawable.ds_ic_watch)
        public val Widget: FlamingoIcon = I(R.drawable.ds_ic_widget)
        public val Wifi: FlamingoIcon = I(R.drawable.ds_ic_wifi)
        public val WifiOff: FlamingoIcon = I(R.drawable.ds_ic_wifi_off)
        public val Wind: FlamingoIcon = I(R.drawable.ds_ic_wind)
        public val Windows: FlamingoIcon = I(R.drawable.ds_ic_windows)
        public val X: FlamingoIcon = I(R.drawable.ds_ic_x)
        public val XCircle: FlamingoIcon = I(R.drawable.ds_ic_x_circle)
        public val XOctagon: FlamingoIcon = I(R.drawable.ds_ic_x_octagon)
        public val XSquare: FlamingoIcon = I(R.drawable.ds_ic_x_square)
        public val Youtube: FlamingoIcon = I(R.drawable.ds_ic_youtube)
        public val Zap: FlamingoIcon = I(R.drawable.ds_ic_zap)
        public val ZapFilledV2: FlamingoIcon = I(R.drawable.ds_ic_zap_filled_v2)
        public val ZapOff: FlamingoIcon = I(R.drawable.ds_ic_zap_off)
        public val ZapV2: FlamingoIcon = I(R.drawable.ds_ic_zap_v2)
        public val ZoomIn: FlamingoIcon = I(R.drawable.ds_ic_zoom_in)
        public val ZoomOut: FlamingoIcon = I(R.drawable.ds_ic_zoom_out)
    }
}

